### ISSUE TITLE
From where did the RTF files come from?

### ISSUE THREAD

**Issue by lucaszanella** [own-pt/openWordnet-PT#124]
I'm reading that you guys used https://github.com/jmccrae/wn-rdf to convert the data to the RTF format. So where is the original data? This RTF format is too strange to read.

Also, is there any way to import this data into NLTK just like wordnet is?

**Comment by arademaker** [comment]
I am assuming you are talking about RDF and not RTF, right ?

we don't use @jmccrae code , our wordnet was encoded in RDF before @jmccrae project. The model we followed and extended was the https://www.w3.org/TR/wordnet-rdf/ the code is https://github.com/own-pt/wordnet2rdf . We used as source the original Princeton files and our own data files. 

Since our wordnet is the Portuguese wordnet at http://compling.hss.ntu.edu.sg/omw/, I believe it is already available in NLTK, see the link about NLTK in this last URL.
